---
deployment:
  tasks:
    - export DEPLOYPATH=/home/binalcnq/
    - /bin/cp -R app $DEPLOYPATH
    - /bin/cp -R bootstrap  $DEPLOYPATH
    - /bin/cp -R config  $DEPLOYPATH
    - /bin/cp -R database  $DEPLOYPATH
    - /bin/cp -R public/*  $DEPLOYPATH/public_html
    - /bin/cp -R resources  $DEPLOYPATH
    - /bin/cp -R routes  $DEPLOYPATH
    - /bin/cp -R storage $DEPLOYPATH
    - /bin/cp -R tests $DEPLOYPATH
    - /bin/cp artisan $DEPLOYPATH
    - /bin/cp composer.json $DEPLOYPATH
